# --- Datasource MySQL de développement ---
spring.datasource.url=jdbc:mysql://localhost:3306/ghe_db_dev
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Initialisation des données de développement ---
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
application.init=true